version: '3'
services:
  shorten-link-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DATABASE: "shorten_link"

  # shorten-link-app:
  #   build: .
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - shorten-link-pg
  #   environment:
  #     DATABASE_URL: "postgresql://postgres:postgres@shorten-link-pg:5432/shorten_link"
